<a href="https://colab.research.google.com/github/akkiharshavardhansai/tmdb-eda-assignment/blob/main/tmdb_eda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import requests
import pandas as pd
import sqlite3
import time
API_KEY = "130daf9c70a975ecdcd243776686cd94"

url = "https://api.themoviedb.org/3/discover/movie"
params = {
    "api_key": API_KEY,
    "language": "en-US",
    "page": 1
}

In [ ]:
movies = []

for page in range(1, 3):
    params["page"] = page
    response = requests.get(url, params=params)

    if response.status_code == 200:
        data = response.json()
        movies.extend(data['results'])

    time.sleep(1)

In [ ]:
print(movies[:2])

[{'adult': False, 'backdrop_path': '/6yeVcxFR0j08vlv2OlL6zbewm4D.jpg', 'genre_ids': [28, 878, 53], 'id': 1265609, 'original_language': 'en', 'original_title': 'War Machine', 'overview': 'On one last grueling mission during Army Ranger training, a combat engineer must lead his unit in a fight against a giant otherworldly killing machine.', 'popularity': 345.151, 'poster_path': '/tlPgDzwIE7VYYIIAGCTUOnN4wI1.jpg', 'release_date': '2026-02-12', 'title': 'War Machine', 'video': False, 'vote_average': 7.3, 'vote_count': 1112}, {'adult': False, 'backdrop_path': '/1fkuBPid72KGS6WmtkEXMftZtkE.jpg', 'genre_ids': [80, 18], 'id': 875828, 'original_language': 'en', 'original_title': 'Peaky Blinders: The Immortal Man', 'overview': 'After his estranged son gets embroiled in a Nazi plot, self-exiled gangster Tommy Shelby must return to Birmingham to save his family — and his nation.', 'popularity': 363.0395, 'poster_path': '/gRMalasZEzsZi4w2VFuYusfSfqf.jpg', 'release_date': '2026-03-05', 'title': 'Peaky Blinders: The Immortal Man', 'video': False, 'vote_average': 7.458, 'vote_count': 349}]

In [ ]:
movies_df = pd.DataFrame(movies)
print(movies_df.columns)

Index(['adult', 'backdrop_path', 'genre_ids', 'id', 'original_language',
       'original_title', 'overview', 'popularity', 'poster_path',
       'release_date', 'title', 'video', 'vote_average', 'vote_count'],
      dtype='object')

In [ ]:
movies = []

for page in range(1, 3):
    params["page"] = page
    response = requests.get(url, params=params)

    print(response.status_code)

    if response.status_code == 200:
        data = response.json()
        movies.extend(data.get('results', []))
    else:
        print(response.text)

    time.sleep(1)

200
200

In [ ]:
movies_df = movies_df[['id', 'title', 'popularity', 'vote_average', 'release_date']]

movies_df.rename(columns={'id': 'movie_id'}, inplace=True)

movies_df.head()

,movie_id,title,popularity,vote_average,release_date
0,1265609,War Machine,345.1510,7.300,2026-02-12
1,875828,Peaky Blinders: The Immortal Man,363.0395,7.458,2026-03-05
2,687163,Project Hail Mary,355.5974,8.201,2026-03-15
3,1159559,Scream 7,326.3154,5.845,2026-02-25
4,1290821,Shelter,318.7599,6.640,2026-01-28

In [ ]:
import sqlite3

conn = sqlite3.connect('movies.db')

movies_df.to_sql('movies', conn, if_exists='replace', index=False)

conn.close()

In [ ]:
conn = sqlite3.connect('movies.db')

movies_df = pd.read_sql("SELECT * FROM movies", conn)

movies_df.head()

,movie_id,title,popularity,vote_average,release_date
0,1265609,War Machine,345.1510,7.300,2026-02-12
1,875828,Peaky Blinders: The Immortal Man,363.0395,7.458,2026-03-05
2,687163,Project Hail Mary,355.5974,8.201,2026-03-15
3,1159559,Scream 7,326.3154,5.845,2026-02-25
4,1290821,Shelter,318.7599,6.640,2026-01-28

In [ ]:
movies_df.head()

,movie_id,title,popularity,vote_average,release_date
0,1265609,War Machine,345.1510,7.300,2026-02-12
1,875828,Peaky Blinders: The Immortal Man,363.0395,7.458,2026-03-05
2,687163,Project Hail Mary,355.5974,8.201,2026-03-15
3,1159559,Scream 7,326.3154,5.845,2026-02-25
4,1290821,Shelter,318.7599,6.640,2026-01-28

In [ ]:
movies_df.describe()

           movie_id  popularity  vote_average
count  4.000000e+01   40.000000     40.000000
mean   1.075653e+06  147.272085      6.263075
std    4.061891e+05   94.031171      1.772063
min    7.451000e+03   49.924900      0.000000
25%    8.669870e+05   85.680800      5.872750
50%    1.196248e+06  114.839350      6.832000
75%    1.319024e+06  149.240100      7.275250
max    1.634301e+06  363.039500      8.201000

In [ ]:
movies_df.isnull().sum()

movie_id        0
title           0
popularity      0
vote_average    0
release_date    0
dtype: int64

In [ ]:
movies_df = pd.DataFrame(movies)

movies_df['genre_ids'].explode().value_counts()

genre_ids
53       17
28       13
27       11
878      10
12       10
80        9
18        8
35        8
9648      7
16        4
10749     2
14        2
10751     2
10770     1
Name: count, dtype: int64

In [ ]:
# genre_ids are numeric IDs from TMDB, not names